//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnvironmentMeasurementSystem.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EnvironmentMeasurementSystem.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerts Produced by Sensors.
        /// </summary>
        internal static string Alerts_Title {
            get {
                return ResourceManager.GetString("Alerts_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        internal static string AlertsDetail_AlertDate {
            get {
                return ResourceManager.GetString("AlertsDetail_AlertDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        internal static string AlertsDetail_AlertDescription {
            get {
                return ResourceManager.GetString("AlertsDetail_AlertDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string AlertsDetail_AlertName {
            get {
                return ResourceManager.GetString("AlertsDetail_AlertName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        internal static string AlertsDetail_AlertType {
            get {
                return ResourceManager.GetString("AlertsDetail_AlertType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert Details.
        /// </summary>
        internal static string AlertsDetail_Title {
            get {
                return ResourceManager.GetString("AlertsDetail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment Measurement System.
        /// </summary>
        internal static string FlyoutHeader_Application_Name {
            get {
                return ResourceManager.GetString("FlyoutHeader_Application_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Alerts.
        /// </summary>
        internal static string Home_Alerts {
            get {
                return ResourceManager.GetString("Home_Alerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Sensors.
        /// </summary>
        internal static string Home_Show_All_Sensors {
            get {
                return ResourceManager.GetString("Home_Show_All_Sensors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only My Sensors.
        /// </summary>
        internal static string Home_Show_Only_My_Sensors {
            get {
                return ResourceManager.GetString("Home_Show_Only_My_Sensors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment Measurement System.
        /// </summary>
        internal static string Home_Title {
            get {
                return ResourceManager.GetString("Home_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogIn.
        /// </summary>
        internal static string LogIn_LogIn {
            get {
                return ResourceManager.GetString("LogIn_LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment Measurement System.
        /// </summary>
        internal static string LogIn_Title {
            get {
                return ResourceManager.GetString("LogIn_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Main_Title {
            get {
                return ResourceManager.GetString("Main_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        internal static string Profile_Hello {
            get {
                return ResourceManager.GetString("Profile_Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Sensors:.
        /// </summary>
        internal static string Profile_My_Sensors {
            get {
                return ResourceManager.GetString("Profile_My_Sensors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string Profile_Title {
            get {
                return ResourceManager.GetString("Profile_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery Level.
        /// </summary>
        internal static string Sensor_BatteryLevel {
            get {
                return ResourceManager.GetString("Sensor_BatteryLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CO2.
        /// </summary>
        internal static string Sensor_Co2 {
            get {
                return ResourceManager.GetString("Sensor_Co2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Sensor_Description {
            get {
                return ResourceManager.GetString("Sensor_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humidity.
        /// </summary>
        internal static string Sensor_Humidity {
            get {
                return ResourceManager.GetString("Sensor_Humidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Sensor_Name {
            get {
                return ResourceManager.GetString("Sensor_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOx.
        /// </summary>
        internal static string Sensor_NOx {
            get {
                return ResourceManager.GetString("Sensor_NOx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PM10.
        /// </summary>
        internal static string Sensor_Pm10 {
            get {
                return ResourceManager.GetString("Sensor_Pm10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PM2.5.
        /// </summary>
        internal static string Sensor_Pm25 {
            get {
                return ResourceManager.GetString("Sensor_Pm25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressure.
        /// </summary>
        internal static string Sensor_Pressure {
            get {
                return ResourceManager.GetString("Sensor_Pressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        internal static string Sensor_Temperature {
            get {
                return ResourceManager.GetString("Sensor_Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Sensor_Type {
            get {
                return ResourceManager.GetString("Sensor_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerts.
        /// </summary>
        internal static string Shell_Menu_Item_Alerts {
            get {
                return ResourceManager.GetString("Shell_Menu_Item_Alerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Shell_Menu_Item_Home {
            get {
                return ResourceManager.GetString("Shell_Menu_Item_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogIn.
        /// </summary>
        internal static string Shell_Menu_Item_LogIn {
            get {
                return ResourceManager.GetString("Shell_Menu_Item_LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogOut.
        /// </summary>
        internal static string Shell_Menu_Item_LogOut {
            get {
                return ResourceManager.GetString("Shell_Menu_Item_LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string Shell_Menu_Item_Profile {
            get {
                return ResourceManager.GetString("Shell_Menu_Item_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Shell_Menu_Item_Settings {
            get {
                return ResourceManager.GetString("Shell_Menu_Item_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment Measurement System.
        /// </summary>
        internal static string Shell_Title {
            get {
                return ResourceManager.GetString("Shell_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no Internet connection. Connect to the Internet and try again..
        /// </summary>
        internal static string Snack_Message_NoInternetConnection {
            get {
                return ResourceManager.GetString("Snack_Message_NoInternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string System_Cancel {
            get {
                return ResourceManager.GetString("System_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical.
        /// </summary>
        internal static string System_Critical {
            get {
                return ResourceManager.GetString("System_Critical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string System_Error {
            get {
                return ResourceManager.GetString("System_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string System_Info {
            get {
                return ResourceManager.GetString("System_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to January.
        /// </summary>
        internal static string System_Month_1 {
            get {
                return ResourceManager.GetString("System_Month_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to October.
        /// </summary>
        internal static string System_Month_10 {
            get {
                return ResourceManager.GetString("System_Month_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to November.
        /// </summary>
        internal static string System_Month_11 {
            get {
                return ResourceManager.GetString("System_Month_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to December.
        /// </summary>
        internal static string System_Month_12 {
            get {
                return ResourceManager.GetString("System_Month_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to February.
        /// </summary>
        internal static string System_Month_2 {
            get {
                return ResourceManager.GetString("System_Month_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to March.
        /// </summary>
        internal static string System_Month_3 {
            get {
                return ResourceManager.GetString("System_Month_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to April.
        /// </summary>
        internal static string System_Month_4 {
            get {
                return ResourceManager.GetString("System_Month_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        internal static string System_Month_5 {
            get {
                return ResourceManager.GetString("System_Month_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to June.
        /// </summary>
        internal static string System_Month_6 {
            get {
                return ResourceManager.GetString("System_Month_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to July.
        /// </summary>
        internal static string System_Month_7 {
            get {
                return ResourceManager.GetString("System_Month_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to August.
        /// </summary>
        internal static string System_Month_8 {
            get {
                return ResourceManager.GetString("System_Month_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to September.
        /// </summary>
        internal static string System_Month_9 {
            get {
                return ResourceManager.GetString("System_Month_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string System_Ok {
            get {
                return ResourceManager.GetString("System_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string System_Warning {
            get {
                return ResourceManager.GetString("System_Warning", resourceCulture);
            }
        }
    }
}
